#!/bin/sh
#
# Sync the time with one online so we have the proper
# time before doing anything. Make sure you're connected
# to the internet first.
#
# https://wiki.archlinux.org/index.php/Installation_guide

set -xe

timedatectl set-ntp true
