#!/bin/sh
#
# Set your timezone and update the hardware clock, assuming
# it is currently set to UTC. Note that if you want to use
# multiple operating systems on the same hardware, you
# shouldn't do this.
#
# Check whether or not your hardware clock (RTC) is localtime:
#   timedatectl | grep local
#
# Change hardware clock to localtime:
#   timedatectl set-local-rtc 1
#
# Change hardware clock back to UTC:
#   timedatectl set-local-rtc 0
#
# Note that RTC (the hardware clock) stands for "Real Time Clock"
#
# https://wiki.archlinux.org/index.php/Installation_guide

set -xe

arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime

arch-chroot /mnt hwclock --systohc
