#!/bin/sh
#
# Save our hardware information with mkinitcpio. This creates
# an initial ramdisk environment that allows us to boot the
# Linux kernel.
#
# https://wiki.archlinux.org/index.php/Installation_guide

set -xe

arch-chroot /mnt mkinitcpio -p linux
