{
  imports = [
    ./boot.nix
    ./cdemu.nix
    ./dual-function-keys.nix
    ./fish.nix
    ./fonts.nix
    ./gamemode.nix
    ./greetd.nix
    ./home-manager.nix
    ./hyprland.nix
    ./locale.nix
    ./logind.nix
    ./mullvad.nix
    ./neovim.nix
    ./networking.nix
    ./nix.nix
    ./packages.nix
    ./piper.nix
    ./pipewire.nix
    ./resolved.nix
    ./starship.nix
    ./stylix.nix
    ./system.nix
    ./systemd.nix
    ./thunar.nix
    ./timezone.nix
    ./user.nix
    ./virtualization.nix
    ./wine.nix
    ./zram.nix
  ];
}
