#!/bin/sh
#
# Format sda1 with an ext4 partition and sda2 with a swap partition.
# Then, enable swap for sda2.
#
# https://wiki.archlinux.org/index.php/Installation_guide

set -xe

mkfs -t ext4 /dev/sda1

mkswap /dev/sda2

swapon /dev/sda2
