#!/bin/sh
#
# Generate the fstab file so that the filesystem is
# automatically mounted on boot.
#
# https://wiki.archlinux.org/index.php/Installation_guide

set -xe

genfstab -U /mnt > /mnt/etc/fstab
