#!/bin/sh
#
# Vim is the standard text editor.
#
# https://wiki.archlinux.org/index.php/Vim

set -xe

sudo pacman -S vim

sudo pacman -S neovim

# Add the `undo` directory for regular vim
mkdir -p ~/.vim/undo

# Install all vim plugins with `vim-plug`. Note that your
# .vimrc should already have a section with the plugins that
# you want to install.
#
# https://github.com/junegunn/vim-plug

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qall
