#!/bin/sh
#
# The `zip` package lets us zip files from the shell. The `unzip`,
# `p7zip`, and `unrar` packages let us uncompress zip files, 7z
# files, and rar files respectfully.
#
# https://wiki.archlinux.org/index.php/Archiving_and_compression

set -xe

sudo pacman -S zip

sudo pacman -S unzip

sudo pacman -S p7zip

sudo pacman -S unrar
