#!/bin/sh
#
# If you are installing Arch Linux in a virtual machine (specifically
# through VirtualBox) then you will need to install the guest utilities
# for certain behavior like auto resolution to work.
#
# https://wiki.archlinux.org/index.php/VirtualBox

set -xe

pacman -S virtualbox-guest-utils virtualbox-guest-modules-arch
