#!/bin/sh
#
# The `rng-tools` package is used to increase entropy and make
# /dev/random faster. This is useful for many programs, including
# [SDDM](https://wiki.archlinux.org/index.php/SDDM).
#
# https://wiki.archlinux.org/index.php/Rng-tools

set -xe

sudo pacman -S rng-tools

systemctl enable rngd.service
