#!/bin/sh
#
# XDG user dirs are a universal way to store files. They are used
# by other programs to determine where to find and save files.
#
# The following directories are created with `xdg-user-dirs`:
#
# Desktop   | Documents | Downloads | Music
# Pictures  | Public    | Templates | Videos
#
# https://wiki.archlinux.org/index.php/Xdg_user_directories

set -xe

sudo pacman -S xdg-user-dirs

xdg-user-dirs-update
