#!/bin/sh
#
# Git is the standard version control system.
#
# `diff-so-fancy` is used to show colorful diffs. These diffs
# look much better than the default, so I highly recommend it.
#
# `tig` is used as a terminal-based GUI for the git commit tree.
# It works really well and supports many vim keybindings out of
# the box.
#
# https://wiki.archlinux.org/index.php/Git

set -xe

sudo pacman -S git

sudo pacman -S diff-so-fancy

sudo pacman -S tig
