#!/bin/sh
#
# If for some reason you want to install zsh, you can do that
# here. However, keep in mind that zsh requires a lot of
# configuration to behave similarly to fish.
#
# In other words, use fish.
#
# https://wiki.archlinux.org/index.php/Zsh

set -xe

pacman -S zsh

pacman -S grml-zsh-config

pacman -S zsh-syntax-highlighting
