#!/bin/sh
#
# This script installs an assortment of common CLI tools that I use
# regularly enough to warrant inclusion.
#
# Note that you could also install `lolcat` if you really wanted to.
#
# https://github.com/junegunn/fzf
# https://github.com/sharkdp/fd
# https://github.com/BurntSushi/ripgrep
# https://github.com/jakubroztocil/httpie
# https://github.com/ogham/exa
# https://github.com/stedolan/jq
# https://github.com/borgbackup/borg
# https://github.com/rg3/youtube-dl

set -xe

sudo pacman -S jq            # JSON manipulation
sudo pacman -S ripgrep       # Faster than ag / ack / grep
sudo pacman -S fzf           # Fuzzy find anything
sudo pacman -S httpie        # Make HTTP requests
sudo pacman -S fd            # Faster alternative to find
sudo pacman -S exa           # Drop-in replacement for ls and tree

sudo pacman -S fdupes        # Find duplicate files
sudo pacman -S bind-tools    # DNS tools like dig

sudo pacman -S ncdu          # Ncurses du (disk usage)
sudo pacman -S borg          # Backup directories
sudo pacman -S youtube-dl    # View online videos in mpv
sudo pacman -S neofetch      # Bragging rights

sudo pacman -S pygmentize    # Command line syntax highlighting (used for 'dog')
