#!/bin/sh
#
# LightDM is a lightweight display manager that just works.
#
# Note that instead of using `lightdm-gtk-greeter-settings`, which
# needs to be run with sudo, you can simply edit the config file
# located at /etc/lightdm/lightdm-gtk-greeter.conf instead.
#
# Note that LightDM is not needed if you use Plasma (which you'd
# want to use with SDDM with instead).
#
# lightdm: The LightDM display manager
# lightdm-gtk-greeter: The greeter for LightDM (GTK)
# lightdm-gtk-greeter-settings: GUI for editing LightDM settings
# light-locker: Prevents leaving ttys vulnerable while locked
#
# https://wiki.archlinux.org/index.php/LightDM

set -xe

pacman -S lightdm

pacman -S lightdm-gtk-greeter

pacman -S lightdm-gtk-greeter-settings

pacman -S light-locker

systemctl enable lightdm.service
