#!/bin/sh
#
# After all these years, Xfce is still one of the best desktop
# environments. Although the defaults are bland, you can customize
# it to look however you want.
#
# Alternatively install the `xfce4-goodies` package if you want
# everything instead of the select few applications I choose here.
#
# Note that Xfce doesn't exactly handle HiDPI well, so you might want
# to use bspwm or Plasma instead.
#
# mousepad: basic text editor
# parole: basic media player
# ristretto: basic image viewer
#
# https://wiki.archlinux.org/index.php/Xfce

set -xe

sudo pacman -S xfce4

sudo pacman -S mousepad

sudo pacman -S parole

sudo pacman -S ristretto

sudo pacman -S xfce4-mpc-plugin

sudo pacman -S xfce4-notifyd

sudo pacman -S xfce4-pulseaudio-plugin

sudo pacman -S xfce4-screenshooter

sudo pacman -S xfce4-taskmanager
