#!/bin/sh
#
# bspwm is the best window manager. It does one thing really
# well and supports running commands directly through the shell.
#
# I used to love bspwm a lot. I still do, but it's not as useful
# now that I know how to use tmux. By using a terminal multiplexer,
# the issue of organizing several terminal windows in one view is
# solved without having to depend on the window manager.
#
# bspwm is still useful when you want a minimal setup with no
# overhead, since it performs exceptionally well compared to other
# desktop environments riddled with features. Plus, it supports
# HiDPI really well, with the exception of some older programs.
#
# The Simple X Hotkey Daemon (sxhkd) is used to make keyboard
# bindings so you can interact with bspwm. Make sure your bspwmrc
# file is executable (chmod +x) as well.
#
# https://wiki.archlinux.org/index.php/Bspwm

set -xe

# Install xorg as the display server (required)
pacman -S xorg-server

# Prerequisite for running bspwm without a display manager
# Remove this line if you're using one
pacman -S xorg-xinit

pacman -S xdo           # Show / hide windows (for polybar)
pacman -S xorg-xprop    # Get window status (for polybar)

pacman -S xclip         # Clipboard manager (to copy with a command)
pacman -S xcape         # Make Caps Lock = Ctrl/ESC

# The actual window manager and hotkey daemon
pacman -S bspwm
pacman -S sxhkd

# compton is the standard compositor.
pacman -S compton

# Terminal emulator
pacman -S rxvt-unicode

yay -S urxvtcd

# polybar is the standard panel.
yay -S polybar
