#!/bin/sh
#
# KDE Plasma is a really nice and feature rich desktop environment
# that also has good HiDPI support.
#
# It includes many applications that the common user may need, as
# well as some games one may find interesting.
#
# Although resource usage is considerably high compared to using just
# a window manager like bspwm, KDE offers many aspects of itself that
# you simply cannot achieve with a window manager without dedicating
# significant time and energy.
#
# To install just the desktop environment and nothing else,
# use the `plasma-desktop` package instead of `plasma`.
#
# The Plasma desktop environment also has great support for multiple
# users out of the box. There is no need to worry about making new
# users manually, as this can be handled through the GUI.
#
# https://wiki.archlinux.org/index.php/KDE

set -xe

pacman -S plasma
