#!/bin/sh
#
# SDDM is the standard display manager for KDE Plasma.
#
# It also has exceptionally well HiDPI support, more so
# than LightDM. The last few lines enable just that. Remove
# them if you're using a regular display.
#
# https://wiki.archlinux.org/index.php/SDDM

set -xe

sudo pacman -S sddm

sudo pacman -S sddm-kcm

systemctl enable sddm.service

echo '[Wayland]'                    >> /etc/sddm.conf
echo 'EnableHiDPI=true'             >> /etc/sddm.conf

echo '[X11]'                        >> /etc/sddm.conf
echo 'EnableHiDPI=true'             >> /etc/sddm.conf
echo 'ServerArguments= -dpi 192'    >> /etc/sddm.conf
