#!/bin/sh
#
# Adapta is a common GTK theme used by many users. There is
# also A KDE theme for consistency across both toolkits.
#
# https://github.com/adapta-project/adapta-gtk-theme
# https://github.com/PapirusDevelopmentTeam/adapta-kde

set -xe

pacman -S adapta-gtk-theme

pacman -S adapta-kde
