#!/bin/sh
#
# Materia is another common theme.
#
# https://github.com/nana-4/materia-theme
# https://github.com/PapirusDevelopmentTeam/materia-kde

set -xe

pacman -S materia-gtk-theme

pacman -S materia-kde
