#!/bin/sh
#
# Crystal is a nice programming language that lets us use
# the usability of Ruby with the performance of C.
#
# `shards` is the official dependency manager for Crystal.
#
# The low level virtual machine (llvm) is used to build
# crystal directly from the source. This is useful when
# we're making changes to the Crystal programming language
# itself.
#
# https://wiki.archlinux.org/index.php/Crystal

set -xe

pacman -S crystal

pacman -S shards

pacman -S llvm
