#!/bin/sh
#
# Rust is a nice programming language that finds many errors
# for us at compile time. This is useful for writing safe code.
#
# The `rustup` package is used over `rust` because this allows us
# to have multiple rust versions at any given time and update them
# as needed.
#
# There are 3 toolchains: stable, beta, and nightly. In this script
# we install the stable toolchain and make it the default.
#
# https://wiki.archlinux.org/index.php/Rust

set -xe

pacman -S rustup

rustup install stable

rustup default stable
