#!/bin/sh
#
# An AUR helper is a way to automate the process below.
#
# `yay` is an AUR helper.
#
# https://wiki.archlinux.org/index.php/AUR_Helpers

set -xe

git clone https://aur.archlinux.org/yay-bin.git

cd yay-bin

vim PKGBUILD

makepkg -si

cd ..

rm -rf yay-bin
