#!/bin/sh
#
# `launch-cmd` is used to "launch" programs from the shell.
# This method of starting programs prevents it from logging to
# the shell and blocking the next command.
#
# https://github.com/silverhammermba/launch

set -xe

yay -S launch-cmd
