#!/bin/sh
#
# As cool as it is to write your papers in a *vim terminal*,
# sometimes the basics just work, and that's all you need to
# get stuff done.
#
# LibreOffice has improved a lot over the years. It also works
# great with KDE. Give it a try.
#
# Note that we use `libreoffice-still` instead of
# `libreoffice-fresh` due to the save window bug with KDE and GTK.
#
# Edit: Actually, maybe writing things with Vim is still the better
# option. This makes whatever you write a lot more portable since
# you use a human readable file format that someone has probably
# written a library for in other languages. You also end up with
# a whole lot better git support.
#
# LibreOffice Math is very difficult to use compared to simply
# using LaTeX. The amount of clicking required for a basic
# formula takes a lot of effort and the cryptic commands used
# in its shell don't follow LaTeX at all.
#
# LibreOffice Base seems like an attempt to bring database
# management to less-savvy users, but traditional command line
# interaction with the database seems like the better option here.
#
# Draw and Impress seem like both are easier to future-proof and
# accomplish with web technologies.
#
# For me, it seems like I'll only use LibreOffice Writer and
# LibreOffice Calc (although even then I'm not so sure since
# there are other data formats out there that I'm familiar
# with and able to work with.
#
# https://wiki.archlinux.org/index.php/Libreoffice

set -xe

sudo pacman -S libreoffice-still
