#!/bin/sh
#
# Code is an open source build of Visual Studio Code. It has a GUI
# similar to Sublime Text but includes the extensibility of Atom.
#
# Unfortunately it is written in JavaScript, so it may be slow at
# times. However, it has nice plugin support, including a plugin
# to use many vim keybindings!
#
# This script assumes you've already installed `yay`. `prlimit` is
# used to increase the number of concurrent files opened since the
# build process takes a substantial amount of resources.
#
# Eventually `code` may or may not become a part of the community
# repository. More on that later.
#
# https://wiki.archlinux.org/index.php/Visual_Studio_Code

set -xe

sudo prlimit --pid $$ --nofile=10000:10000

yay -S code
