#!/bin/sh
# New Start: A modern Arch workflow built with an emphasis on functionality.
# Copyright (C) 2018 Donovan Glover

export SXHKD_SHELL="/usr/bin/bash"
export XCURSOR_THEME="breeze_cursors"
export XDG_DATA_DIRS="/usr/share:/usr/share:/usr/local/share"

sxhkd &

bspc monitor -d      

bspc config split_ratio          0.50

# When monocle mode is enabled, don't show borders or gaps (i.e. let it
# take up the full available space on the screen).
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Always focus the window under the cursor
# while moving the mouse, similar to i3
bspc config focus_follows_pointer true

# Make caps lock work as ctrl
xmodmap ~/.xmodmap

# Make caps lock (left ctrl) work as escape
xcape -e 'Control_L=Escape'

# Change the default X shaped cursor to a pointer
xsetroot -cursor_name left_ptr

# Set a temporary black background to avoid flash
~/.config/feh/tile.sh 000000

# If running with VirtualBox client utilities, start them.
# Useful for automatically changing display resolution, etc.
if hash VBoxClient-all 2>/dev/null; then
  VBoxClient-all
fi

# Set the color scheme to a sane default.
wal -o ~/.config/wal/done.sh --theme base16-tomorrow-night

# Never blank the screen (disable power saving)
xset s off -dpms

# Start compton
compton -b

# Start polybar and other things based on DPI
~/.config/xeventbind/on-resolution-change.sh

if hash xeventbind 2>/dev/null; then
  xeventbind resolution $HOME/.config/xeventbind/on-resolution-change.sh &
fi

# bspc rules
bspc rule -a mpv            state=floating
bspc rule -a feh            state=floating
bspc rule -a kitty:floating state=floating

bspc rule -a kwrite         state=floating
bspc rule -a ark            state=floating
bspc rule -a kmag           state=floating
bspc rule -a kcharselect    state=floating
bspc rule -a Onboard        state=floating sticky=on
