#!/bin/sh
# New Start: A modern Arch workflow built with an emphasis on functionality.
# Copyright (C) 2018-2022 Donovan Glover

export SXHKD_SHELL="/usr/bin/bash"
export XCURSOR_THEME="phinger-cursors"
export XDG_DATA_DIRS="/usr/share:/usr/share:/usr/local/share"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus
export XSECURELOCK_SAVER=saver_mpv

sxhkd &

# Use specific icons for the first four desktops and the other 6 as ad hoc ones
bspc monitor -d     五 六 七 八 九 十

bspc config split_ratio          0.50

# When monocle mode is enabled, don't show borders or gaps (i.e. let it
# take up the full available space on the screen).
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Always focus the window under the cursor
# while moving the mouse, similar to i3
bspc config focus_follows_pointer true

# Make caps lock work as ctrl
xmodmap ~/.xmodmap

# Make caps lock (left ctrl) work as escape
xcape -e 'Control_L=Escape'

# Change the default X shaped cursor to a pointer
xsetroot -cursor_name left_ptr

# Set a temporary black background to avoid flash
~/.config/feh/tile.sh 000000

# If running with VirtualBox client utilities, start them.
# Useful for automatically changing display resolution, etc.
if hash VBoxClient-all 2>/dev/null; then
  VBoxClient-all
fi

# Set the color scheme to a sane default.
wal -o ~/.config/wal/done.sh --theme base16-tomorrow-night

# Never blank the screen (disable power saving)
xset s off -dpms

# Start picom (prevents screen tearing)
picom -b

# Start polybar and other things based on DPI
# Get the host width
HOST_WIDTH=$(bspc query -T -m | jq '.rectangle.width')

CURSOR_THEME=${XCURSOR_THEME:-phinger-cursors}

# If the DPI is not set, set it to 96 by default
if [ -z "$(xrdb -query | grep dpi)" ]; then
  X_DPI=96
fi

# Determine the DPI based on screen width
if [ "$HOST_WIDTH" -eq "1920" ]; then
  X_DPI=96
fi

if [ "$HOST_WIDTH" -eq "3840" ]; then
  X_DPI=192
fi

# Reposition the desktop background
~/.fehbg &

# If the DPI needs to be changed, change it
if [ "$X_DPI" ]; then
  echo "Xft.dpi:$X_DPI" | xrdb -merge

  # Change the X cursor size as well
  # NOTE: For full effect, this needs to be used in combination with XCURSOR_SIZE.
  # NOTE: ($X_DPI / 6) here means that 4k will use cursor size 32, so it will appear
  #       about half the size of the 1080p cursor. If this is not what you want, use
  #       cursor size 64 instead.
  xsetroot -xcf "/usr/share/icons/$CURSOR_THEME/cursors/left_ptr" "$(($X_DPI / 6))"
fi

~/.config/polybar/launch.sh main &

# bspc rules
bspc rule -a mpv            state=floating
bspc rule -a feh            state=floating
bspc rule -a kitty:floating state=floating

bspc rule -a kwrite         state=floating
bspc rule -a ark            state=floating
bspc rule -a kmag           state=floating
bspc rule -a kcharselect    state=floating
bspc rule -a Onboard        state=floating sticky=on

# Configure touchpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" 0

# Auto-hide the mouse cursor when inactive
unclutter &

# Start the notification daemon
dunst &

# Start fcitx
fcitx5 &

# Auto-mount partitions
udiskie &
