#!/bin/sh
# New Start: A modern Arch workflow built with an emphasis on functionality.
# Copyright (C) 2018 Donovan Glover

export SXHKD_SHELL="/usr/bin/bash"

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        2
bspc config window_gap          30

bspc config split_ratio          0.50

# Use monocle mode by default on single window desktops.
bspc config single_monocle       true

# When monocle mode is enabled, don't show borders or gaps (i.e. let it
# take up the full available space on the screen).
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Always focus the window under the cursor
# while moving the mouse, similar to i3
bspc config focus_follows_pointer true

# Make caps lock work as ctrl
xmodmap ~/.xmodmap

# Make caps lock (left ctrl) work as escape
xcape -e 'Control_L=Escape'

# If we're in KDE Plasma, then add bottom padding for
# the panel at the bottom.
if [ "$XDG_CURRENT_DESKTOP" == "KDE" ]; then
  bspc config window_gap          20
  bspc config bottom_padding      60

  # Make the application menu float instead of tile
  bspc rule -a plasmashell    state=floating border=off

else
  # If running with VirtualBox client utilities, start them.
  # Useful for automatically changing display resolution, etc.
  if hash VBoxClient-all 2>/dev/null; then
    VBoxClient-all
  fi

  # Overall look (top_padding from polybar)
  bspc config top_padding         80
  bspc config border_width        10
  bspc config window_gap          20

  # Never blank the screen (disable power saving)
  xset s off -dpms

  # Start compton
  compton -b

  # Set the desktop background
  ~/.fehbg &

  # Start polybar
  ~/.config/polybar/launch.sh

  # Start a terminal
  urxvtcd &
fi

# bspc rules
bspc rule -a mpv            state=floating
bspc rule -a feh            state=floating

bspc rule -a kwrite         state=floating
bspc rule -a ark            state=floating
bspc rule -a kmag           state=floating
bspc rule -a kcharselect    state=floating

# TODO: The colors below can probably be re-written to accept values
# from the .Xresources file.

# [colors]
bspc config normal_border_color     "#C0C5CE"
bspc config active_border_color     "#FFFFFF"
bspc config focused_border_color    "#FFFFFF"
bspc config presel_feedback_color   "#C0C5CE"
