#!/bin/sh
#
# Install the base packages to the mounted partition (the newly
# created filesystem).
#
# We also install grub and fish since grub is the boot loader
# and fish is the preferred shell.
#
# https://wiki.archlinux.org/index.php/Installation_guide

set -xe

pacstrap /mnt base base-devel grub fish
