#!/bin/sh
#
# There are 3 major themes in the current Linux community.
# These themes have support for both GTK and KDE and use
# the Papirus icon theme set. The result is very nice and
# usually works out of the box. Thanks to everyone that
# contributed to these projects!
#
# In KDE, Adapta is the light theme, Arc is the dark theme,
# and Materia is the darker theme.
#
# Make sure to change both the KDE and GTK themes.
#
# In Plasma, to change the KDE theme:
#   System Settings > Workspace Theme > Look and Feel
#
# To change the GTK theme:
#   System Settings > Application Style > GNOME Application Style (GTK)
# Here there are 4 options you must change:
#   GTK2 Theme, GTK3 Theme, Icon theme, and Fallback theme.
#
# https://wiki.archlinux.org/index.php/Icons
# https://wiki.archlinux.org/index.php/GTK%2B#Configuration_tools
# https://wiki.archlinux.org/index.php/Uniform_Look_for_QT_and_GTK_Applications
# https://github.com/adapta-project/adapta-gtk-theme
# https://github.com/PapirusDevelopmentTeam/adapta-kde
# https://github.com/horst3180/arc-theme
# https://github.com/PapirusDevelopmentTeam/arc-kde
# https://github.com/nana-4/materia-theme
# https://github.com/PapirusDevelopmentTeam/materia-kde
# https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

set -xe

sudo pacman -S adapta-kde adapta-gtk-theme

sudo pacman -S arc-kde arc-gtk-theme

sudo pacman -S materia-kde materia-gtk-theme

sudo pacman -S papirus-icon-theme
