#!/bin/sh

set -xe

# Change the working directory to the location of this script
# Then, move up to the root directory of the git repo
cd "$(dirname "$0")"
cd ../..

# Raise an error if no environment is given
if [ "$#" -ne 1 ]; then
    echo 'Usage: sh ./path/to/bootstrap <environment>'
    exit 1
fi

# Install common packages if tig isn't found (one of the common packages)
if ! hash tig 2>/dev/null; then
    echo 'Installing common packages...'
    sudo pacman -Syu --needed - < ./packages/arch/common

    echo 'Stowing common dotfiles...'
    stow -S common --dir=dots --target=$HOME --no-folding --verbose=2

    echo 'Configuring common packages...'
    sh ./scripts/006-common
fi

# Install yay if it isn't found (needed for AUR and bspwm)
if ! hash yay 2>/dev/null; then
    echo 'Installing yay...'
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepkg -si
    cd ..
    rm -r yay-bin
fi

# Install plasma
if [ $1 == "plasma" ]; then
    echo 'Installing plasma packages...'
    sudo pacman -Syu --needed --ignore discover - < ./packages/arch/plasma

    exit 0
fi

# Install bspwm
if [ $1 == "bspwm" ]; then
    echo 'Installing bspwm packages...'
    sudo pacman -Syu --needed - < ./packages/arch/bspwm

    echo 'Installing bspwm packages from AUR...'
    yay -S polybar rtv shotgun launch-cmd

    echo 'Stowing bspwm dotfiles...'
    stow -S bspwm --dir=dots --target=$HOME --no-folding --verbose=2

    exit 0
fi

# Throw an error if the script couldn't find a valid environment to use
echo 'Invalid environment specified. Must be either "plasma" or "bspwm"'
exit 1
